AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS lambda for auto-formation purpose.
Resources:
  hellojava:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://acg-devops-joseph/c53179336ffe744cef3f05cfe2c987ad
      Handler: example.HelloHandler
      Runtime: java11
      Description: Java function
      FunctionName: hello-java
      MemorySize: 128
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambdaReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
  hellojava2:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: s3://acg-devops-joseph/c53179336ffe744cef3f05cfe2c987ad
      Handler: example2.HelloHandler2
      Runtime: java11
      Description: Java function
      FunctionName: hello-java2
      MemorySize: 128
      Timeout: 10
      Policies:
      - AWSLambdaBasicExecutionRole
      - AWSLambdaReadOnlyAccess
      - AWSXrayWriteOnlyAccess
      - AWSLambdaVPCAccessExecutionRole
      Tracing: Active
